import * as fs from "node:fs/promises";
import * as path from "node:path";

import { build } from "esbuild";

const root = process.cwd();
const clientDirectory = path.join(root, "dist", "client");

await fs.rm(clientDirectory, { recursive: true, force: true });
await fs.cp(path.join(root, "public"), clientDirectory, { recursive: true });
await fs.mkdir(path.join(clientDirectory, "assets"), { recursive: true });

let result = await build({
  absWorkingDir: root,
  entryPoints: {
    entry: "app/assets/entry.ts",
    "radio-room": "app/assets/radio-room.tsx",
  },
  outdir: "dist/client/assets",
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  splitting: true,
  entryNames: "[name]-[hash]",
  chunkNames: "chunk-[hash]",
  metafile: true,
  sourcemap: true,
  minify: process.env.NODE_ENV === "production",
  jsx: "automatic",
  jsxImportSource: "remix/ui",
});

let entryHref = browserEntryHref(result.metafile, "app/assets/entry.ts");
let radioRoomHref = browserEntryHref(result.metafile, "app/assets/radio-room.tsx");
assertBrowserExport(result.metafile, "app/assets/radio-room.tsx", "RadioRoom");
await fs.writeFile(
  path.join(root, "app", "assets", "build-manifest.ts"),
  `// Generated by scripts/build.mjs. Do not edit.\nexport const browserAssets = {\n  entry: ${JSON.stringify(entryHref)},\n  radioRoom: ${JSON.stringify(radioRoomHref)},\n} as const;\n`,
);

function browserEntryHref(metafile, entryPoint) {
  let output = browserEntry(metafile, entryPoint)[0];
  return "/" + path.relative(clientDirectory, path.resolve(root, output)).split(path.sep).join("/");
}

function assertBrowserExport(metafile, entryPoint, exportName) {
  let [, metadata] = browserEntry(metafile, entryPoint);
  if (!metadata.exports.includes(exportName)) {
    throw new Error(`Browser build for ${entryPoint} does not export ${exportName}`);
  }
}

function browserEntry(metafile, entryPoint) {
  let entry = Object.entries(metafile.outputs).find(
    ([, metadata]) => metadata.entryPoint === entryPoint,
  );
  if (!entry) throw new Error(`Browser build did not emit ${entryPoint}`);
  return entry;
}
