import { css } from "remix/ui";

import {
  desktopControlStyle,
  desktopIconStyle,
  desktopSmallControlStyle,
  desktopStyle,
} from "../ui/desktop/styles.ts";
import { desktopColor } from "../ui/desktop/theme.ts";

export const radioStyle = {
  window: desktopStyle.window,
  titleBar: desktopStyle.titleBar,
  panel: desktopStyle.panel,
  messageCard: desktopStyle.messageCard,
  messageHeader: desktopStyle.messageLabel,
  primaryButton: desktopStyle.primaryButton,
  smallPrimaryButton: desktopStyle.smallPrimaryButton,
  input: desktopStyle.input,
  fileInput: desktopStyle.visuallyHidden,

  shell: css({
    width: "min(960px, 100%)",
    margin: "0 auto",
    display: "grid",
    minHeight: 0,
    boxSizing: "border-box",
    gridTemplateRows: "28px auto minmax(0, 1fr) auto",
  }),
  pageShell: css({ height: "90vh" }),
  previewShell: css({ height: "600px" }),
  topBar: css({ justifyContent: "flex-end" }),
  roomLink: css({ color: "#fff", marginRight: "auto" }),
  statusPill: css({
    width: "12px",
    flex: "0 0 12px",
    height: "100%",
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    position: "relative",
    fontSize: "12px",
    "&::before": {
      content: '""',
      boxSizing: "border-box",
      flex: "0 0 12px",
      width: "12px",
      height: "12px",
      border: "1px solid rgba(31, 42, 49, 0.72)",
      borderRadius: "50%",
      boxShadow: "0 1px rgba(255, 255, 255, 0.5) inset, 0 1px 2px rgba(0, 0, 0, 0.35)",
    },
    '&[data-tone="offline"]::before': {
      background: "radial-gradient(circle at 35% 30%, #ffd2cc, #d9574f 55%, #8f2722)",
    },
    '&[data-tone="syncing"]::before': {
      background: "radial-gradient(circle at 35% 30%, #fff2bd, #d9ad35 55%, #8f6818)",
    },
    '&[data-tone="online"]::before': {
      background: "radial-gradient(circle at 35% 30%, #d5f6dc, #43a85b 55%, #236b34)",
    },
    "& > span": {
      position: "absolute",
      top: "50%",
      right: "20px",
      opacity: 0,
      transform: "translate(4px, -50%)",
      transition: "opacity 120ms ease, transform 120ms ease",
      whiteSpace: "nowrap",
      pointerEvents: "none",
      display: "flex",
      alignItems: "center",
    },
    "& > span > i": {
      padding: "0 4px",
      opacity: 0.42,
      fontStyle: "normal",
    },
    "&:hover > span": {
      opacity: 1,
      transform: "translate(0, -50%)",
    },
  }),
  nowPlaying: css({
    margin: "6px",
    display: "grid",
    minHeight: "118px",
    position: "relative",
    overflow: "hidden",
    background: `linear-gradient(90deg, ${desktopColor.paper}, color-mix(in oklab, ${desktopColor.accentSoft}, ${desktopColor.paper} 72%), ${desktopColor.paper})`,
  }),
  audioVisualizer: css({
    position: "absolute",
    inset: 0,
    display: "block",
    width: "100%",
    height: "100%",
    color: desktopColor.accent,
    pointerEvents: "none",
  }),
  trackMeta: css({
    minWidth: 0,
    minHeight: "116px",
    display: "grid",
    alignItems: "center",
    padding: "10px 12px",
    position: "relative",
    zIndex: 1,
    boxSizing: "border-box",
  }),
  trackTitle: css({
    margin: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "clip",
    fontWeight: 400,
  }),
  iconButton: css({
    ...desktopControlStyle.button,
    width: "34px",
    overflow: "hidden",
    textIndent: "48px",
    whiteSpace: "nowrap",
    position: "relative",
    "&::after": {
      ...desktopIconStyle,
      position: "absolute",
      inset: 0,
      display: "grid",
      placeItems: "center",
      textIndent: 0,
      fontSize: "16px",
    },
    '&[aria-label="Wake audio"]::after': { content: '"power_settings_new"' },
    '&[aria-label="Sync playback"]::after': { content: '"sync"' },
  }),
  nudgeButton: css({
    ...desktopSmallControlStyle,
    width: "42px",
    height: "22px",
    padding: 0,
    borderColor: "#9aa5aa",
    background: "linear-gradient(#f6f9f9, #e5ebed)",
    boxShadow: "none",
    color: "#4f5b60",
    fontSize: "10px",
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
    "&:hover": {
      borderColor: desktopColor.line,
      color: desktopColor.ink,
    },
  }),
  playToggle: css({
    ...desktopControlStyle.button,
    width: "34px",
    background: `linear-gradient(${desktopColor.accentSoft}, #9fdde6)`,
    overflow: "hidden",
    textIndent: "48px",
    whiteSpace: "nowrap",
    position: "relative",
    "&::after": {
      ...desktopIconStyle,
      content: '"play_arrow"',
      position: "absolute",
      inset: 0,
      display: "grid",
      placeItems: "center",
      textIndent: 0,
      fontSize: "14px",
      fontVariationSettings: '"FILL" 1',
    },
    '&[aria-label="Pause"]::after': { content: '"pause"', fontSize: "16px" },
  }),
  smallDangerButton: css({
    ...desktopSmallControlStyle,
    width: "24px",
    height: "24px",
    padding: 0,
    overflow: "hidden",
    textIndent: "48px",
    whiteSpace: "nowrap",
    position: "relative",
    "&::after": {
      ...desktopIconStyle,
      content: '"close"',
      position: "absolute",
      inset: 0,
      display: "grid",
      placeItems: "center",
      textIndent: 0,
      fontSize: "12px",
    },
  }),
  volume: css({
    display: "grid",
    gridTemplateColumns: "30px 92px 34px",
    gap: "6px",
    alignItems: "center",
    justifySelf: "end",
    fontSize: "14px",
    "& input": { ...desktopControlStyle.range, width: "92px", minWidth: 0 },
    "@media (max-width: 560px)": {
      justifySelf: "stretch",
      gridTemplateColumns: "30px minmax(0, 1fr) 34px",
      "& input": { width: "100%" },
    },
  }),
  seek: css({
    display: "grid",
    gridTemplateColumns: "48px minmax(0, 1fr) 48px",
    gap: "8px",
    alignItems: "center",
    width: "100%",
    marginInline: 0,
    "& input": { ...desktopControlStyle.range, minWidth: 0 },
    "& input:disabled": { opacity: 0.35 },
  }),
  content: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 240px",
    gap: "6px",
    minHeight: 0,
    overflow: "hidden",
    alignItems: "stretch",
    padding: "0 6px 6px",
    "@media (max-width: 820px)": {
      gridTemplateColumns: "1fr",
      gridTemplateRows: "minmax(0, 2fr) minmax(96px, 1fr)",
    },
  }),
  queuePanel: css({
    minHeight: 0,
    overflow: "hidden",
    display: "grid",
    gridTemplateRows: "38px minmax(0, 1fr)",
  }),
  sectionHeader: css({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: "38px",
    padding: "0 10px",
    borderBottom: `1px solid ${desktopColor.line}`,
    background: `linear-gradient(${desktopColor.paper}, ${desktopColor.wash})`,
    "& h2": { margin: 0, fontSize: "14px", fontWeight: 400 },
    "& button": { flex: "0 0 auto" },
  }),
  queueScroll: css({ overflow: "auto", overscrollBehavior: "contain", minHeight: 0 }),
  listeners: css({
    display: "grid",
    gridTemplateRows: "38px minmax(0, 1fr)",
    alignSelf: "stretch",
    minHeight: 0,
    overflow: "hidden",
  }),
  utilityTitle: css({
    margin: 0,
    minHeight: "38px",
    display: "grid",
    alignItems: "center",
    padding: "0 10px",
    fontSize: "14px",
    fontWeight: 400,
    borderBottom: `1px solid ${desktopColor.line}`,
    background: `linear-gradient(${desktopColor.paper}, ${desktopColor.wash})`,
  }),
  list: css({
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "grid",
    alignContent: "start",
    gridAutoRows: "minmax(34px, auto)",
    minHeight: 0,
    overflow: "auto",
    overscrollBehavior: "contain",
  }),
  queueList: css({ listStyle: "none", padding: 0, margin: 0, display: "grid" }),
  queueItem: css({
    display: "grid",
    gridTemplateColumns: "34px minmax(0, 1fr) 34px",
    gap: 0,
    alignItems: "center",
    minHeight: "48px",
    padding: 0,
    borderBottom: `1px solid ${desktopColor.wash}`,
    position: "relative",
    overflow: "hidden",
    "& > *:not([aria-hidden])": { position: "relative", zIndex: 1 },
    '&[data-dragging="true"]': { opacity: 0.46 },
    '&[data-drop-position="before"]::before, &[data-drop-position="after"]::after': {
      content: '""',
      position: "absolute",
      zIndex: 3,
      left: 0,
      right: 0,
      height: "3px",
      background: desktopColor.accent,
      pointerEvents: "none",
    },
    '&[data-drop-position="before"]::before': { top: 0 },
    '&[data-drop-position="after"]::after': { bottom: 0 },
  }),
  trackProgress: css({
    position: "absolute",
    zIndex: 0,
    inset: 0,
    right: "auto",
    background: `linear-gradient(90deg, ${desktopColor.accentSoft}, color-mix(in oklab, ${desktopColor.accentSoft}, transparent 55%))`,
    transition: "width 120ms linear",
    pointerEvents: "none",
  }),
  activeQueueItem: css({
    background: desktopColor.wash,
  }),
  trackButton: css({
    gridColumn: 2,
    gridRow: 1,
    border: 0,
    background: "transparent",
    width: "100%",
    height: "100%",
    color: "inherit",
    font: "inherit",
    cursor: "pointer",
    display: "grid",
    gridTemplateColumns: "36px minmax(0, 1fr)",
    gap: "6px",
    alignItems: "center",
    minWidth: 0,
    textAlign: "left",
    padding: "8px 8px 8px 0",
    "&:disabled": { cursor: "default", opacity: 0.62 },
    "&:focus-visible": {
      outline: `2px solid ${desktopColor.accent}`,
      outlineOffset: "-2px",
    },
  }),
  editingTrackButton: css({
    pointerEvents: "none",
    cursor: "default",
    "& > :last-child": { visibility: "hidden" },
  }),
  dragHandle: css({
    gridColumn: 1,
    gridRow: 1,
    width: "24px",
    height: "24px",
    padding: 0,
    border: 0,
    color: "#607077",
    background: "transparent",
    cursor: "grab",
    overflow: "hidden",
    textIndent: "48px",
    whiteSpace: "nowrap",
    position: "relative",
    justifySelf: "center",
    "&::after": {
      ...desktopIconStyle,
      content: '"drag_indicator"',
      position: "absolute",
      inset: 0,
      display: "grid",
      placeItems: "center",
      textIndent: 0,
      fontSize: "17px",
    },
    "&:hover": { color: desktopColor.ink, background: desktopColor.wash },
    "&:active": { cursor: "grabbing" },
    "&:focus-visible": {
      outline: `2px solid ${desktopColor.accent}`,
      outlineOffset: "-2px",
    },
  }),
  queueIndex: css({ color: "#607077", fontVariantNumeric: "tabular-nums" }),
  queueTrack: css({
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "8px",
    alignItems: "baseline",
    "& > span": { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    "& > small": { color: "#526168", fontSize: "11px", fontVariantNumeric: "tabular-nums" },
  }),
  queueEditInput: css({
    gridColumn: 2,
    gridRow: 1,
    width: "calc(100% - 50px)",
    minWidth: 0,
    height: "30px",
    marginLeft: "42px",
    padding: "0 7px",
    alignSelf: "center",
    borderColor: desktopColor.line,
    borderRadius: "2px",
    position: "relative",
    zIndex: 2,
  }),
  trackMenuButton: css({
    gridColumn: 3,
    gridRow: 1,
    width: "24px",
    height: "24px",
    padding: 0,
    border: 0,
    borderRadius: 0,
    background: "transparent",
    color: "#607077",
    boxShadow: "none",
    alignSelf: "center",
    justifySelf: "center",
    cursor: "pointer",
    '&:hover, &[aria-expanded="true"]': {
      color: desktopColor.ink,
      background: desktopColor.wash,
    },
    "&:focus-visible": {
      outline: `2px solid ${desktopColor.accent}`,
      outlineOffset: "-2px",
    },
  }),
  trackMenuGlyph: css({
    ...desktopIconStyle,
    display: "block",
    fontSize: "17px",
  }),
  trackMenuPopover: css({
    margin: 0,
    padding: 0,
    border: 0,
    background: "transparent",
    overflow: "visible",
  }),
  trackMenuList: css({
    minWidth: "128px",
    display: "grid",
    gap: 0,
    padding: "2px",
    color: desktopColor.ink,
    background: desktopColor.paper,
    border: `1px solid ${desktopColor.line}`,
    borderRadius: "3px",
    boxShadow: "0 2px 4px rgba(31, 42, 49, 0.18)",
    outline: "none",
    fontSize: "12px",
  }),
  trackMenuItem: css({
    minHeight: "25px",
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr)",
    gap: "3px",
    alignItems: "center",
    padding: "0 6px",
    cursor: "pointer",
    border: 0,
    borderRadius: "2px",
    background: "transparent",
    boxShadow: "none",
    userSelect: "none",
    '&[data-highlighted="true"]': {
      background: desktopColor.wash,
    },
    '&[aria-disabled="true"]': {
      opacity: 0.48,
      cursor: "default",
    },
  }),
  trackMenuItemIcon: css({
    ...desktopIconStyle,
    color: "#607077",
    fontSize: "14px",
  }),
  person: css({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
    minHeight: "34px",
    boxSizing: "border-box",
    padding: "5px 8px",
    borderBottom: `1px solid ${desktopColor.wash}`,
    background: "#fff",
    "& small": { color: "#465156" },
  }),
  controlBar: css({
    display: "grid",
    gap: "6px",
    padding: "6px",
    background: "#edf3f4",
    borderTop: `1px solid ${desktopColor.line}`,
    gridTemplateColumns: "minmax(0, 1fr) 188px",
    alignItems: "center",
    "& > div": { gridColumn: "1 / -1" },
    "@media (max-width: 560px)": { gridTemplateColumns: "1fr" },
  }),
  transport: css({
    display: "flex",
    gap: "5px",
    alignItems: "center",
  }),
  nudgeControls: css({
    display: "flex",
    alignItems: "center",
    gap: "4px",
    marginLeft: "auto",
  }),
  nudgeOffset: css({
    width: "48px",
    textAlign: "center",
    color: "#526066",
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
    '&[data-zero="true"]': {
      visibility: "hidden",
    },
  }),
} as const;
