import { css } from 'remix/ui'

import { desktopControlStyle, desktopStyle } from '../ui/desktop/styles.ts'
import { desktopColor } from '../ui/desktop/theme.ts'

export const radioStyle = {
  window: desktopStyle.window,
  titleBar: desktopStyle.titleBar,
  panel: desktopStyle.panel,
  messageCard: desktopStyle.messageCard,
  messageHeader: desktopStyle.messageLabel,
  primaryButton: desktopStyle.primaryButton,
  input: desktopStyle.input,
  fileInput: desktopStyle.visuallyHidden,

  shell: css({
    width: 'min(960px, 100%)',
    margin: '0 auto',
    display: 'grid',
    minHeight: 'min(760px, calc(100vh - 32px))',
    gridTemplateRows: '28px auto minmax(0, 1fr) auto',
    '@media (max-width: 720px)': { minHeight: 'calc(100vh - 16px)' },
  }),
  topBar: css({ justifyContent: 'space-between' }),
  brand: css({
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    textTransform: 'lowercase',
    '& strong': { color: desktopColor.accentSoft },
  }),
  statusPill: css({
    display: 'flex',
    gap: '8px',
    fontSize: '13px',
    '& span': {
      borderLeft: '1px solid rgba(255,255,255,0.45)',
      paddingLeft: '8px',
    },
    '@media (max-width: 560px)': { display: 'none' },
  }),
  nowPlaying: css({ margin: '6px', display: 'grid', minHeight: '118px' }),
  trackMeta: css({ minWidth: 0, padding: '8px 10px' }),
  trackTitle: css({
    margin: '4px 0',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'clip',
    fontWeight: 400,
  }),
  status: css({ margin: 0, color: '#465156', fontSize: '14px' }),
  iconButton: css({
    ...desktopControlStyle.button,
    width: '34px',
    overflow: 'hidden',
    textIndent: '48px',
    whiteSpace: 'nowrap',
    position: 'relative',
    '&::after': {
      position: 'absolute',
      inset: 0,
      display: 'grid',
      placeItems: 'center',
      textIndent: 0,
    },
    '&[aria-label="Wake audio"]::after': { content: '"!"' },
    '&[aria-label="Sync playback"]::after': { content: '"S"' },
  }),
  playToggle: css({
    ...desktopControlStyle.button,
    width: '34px',
    background: `linear-gradient(${desktopColor.accentSoft}, #9fdde6)`,
    overflow: 'hidden',
    textIndent: '48px',
    whiteSpace: 'nowrap',
    position: 'relative',
    '&::after': {
      content: '">"',
      position: 'absolute',
      inset: 0,
      display: 'grid',
      placeItems: 'center',
      textIndent: 0,
    },
    '&[aria-label="Pause"]::after': { content: '"||"' },
  }),
  dangerButton: css({
    ...desktopControlStyle.button,
    width: '28px',
    height: '24px',
    overflow: 'hidden',
    textIndent: '48px',
    whiteSpace: 'nowrap',
    position: 'relative',
    '&::after': {
      content: '"x"',
      position: 'absolute',
      inset: 0,
      display: 'grid',
      placeItems: 'center',
      textIndent: 0,
    },
  }),
  volume: css({
    display: 'grid',
    gridTemplateColumns: '30px 92px 34px',
    gap: '6px',
    alignItems: 'center',
    justifySelf: 'end',
    fontSize: '14px',
    background: desktopColor.paper,
    borderLeft: `1px solid ${desktopColor.line}`,
    paddingLeft: '8px',
    '& input': { ...desktopControlStyle.range, width: '92px', minWidth: 0 },
    '@media (max-width: 560px)': {
      justifySelf: 'stretch',
      gridTemplateColumns: '30px minmax(0, 1fr) 34px',
      '& input': { width: '100%' },
    },
  }),
  seek: css({
    display: 'grid',
    gridTemplateColumns: '48px minmax(0, 1fr) 48px',
    gap: '8px',
    alignItems: 'center',
    width: '100%',
    marginInline: 0,
    '& input': { ...desktopControlStyle.range, minWidth: 0 },
    '& input:disabled': { opacity: 0.35 },
  }),
  content: css({
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 240px',
    gap: '6px',
    minHeight: 0,
    alignItems: 'stretch',
    padding: '0 6px 6px',
    '@media (max-width: 820px)': {
      gridTemplateColumns: '1fr',
      gridTemplateRows: 'minmax(0, 1fr) auto',
    },
  }),
  queuePanel: css({
    minHeight: 0,
    overflow: 'hidden',
    display: 'grid',
    gridTemplateRows: '38px auto minmax(0, 1fr)',
  }),
  sectionHeader: css({
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: '38px',
    padding: '0 10px',
    borderBottom: `1px solid ${desktopColor.line}`,
    background: `linear-gradient(${desktopColor.paper}, ${desktopColor.wash})`,
    '& h2': { margin: 0, fontSize: '14px', fontWeight: 400 },
    '& span': { fontSize: '12px' },
  }),
  upload: css({
    display: 'flex',
    justifyContent: 'flex-end',
    padding: '6px',
    background: '#edf3f4',
    borderBottom: `1px solid ${desktopColor.line}`,
    '& button': { width: '150px' },
    '@media (max-width: 560px)': { '& button': { width: '100%' } },
  }),
  queueScroll: css({ overflow: 'auto', minHeight: 0 }),
  listeners: css({
    display: 'grid',
    gridTemplateRows: '46px minmax(0, 1fr)',
    alignSelf: 'stretch',
    minHeight: 0,
    '@media (max-width: 820px)': { minHeight: '96px' },
  }),
  utilityTitle: css({
    margin: 0,
    display: 'grid',
    alignItems: 'center',
    padding: '0 10px',
    fontSize: '14px',
    fontWeight: 400,
    borderBottom: `1px solid ${desktopColor.line}`,
    background: `linear-gradient(${desktopColor.paper}, ${desktopColor.wash})`,
  }),
  list: css({ listStyle: 'none', padding: 0, margin: 0, display: 'grid' }),
  queueList: css({ listStyle: 'none', padding: 0, margin: 0, display: 'grid' }),
  queueItem: css({
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 32px',
    gap: '4px',
    alignItems: 'center',
    minHeight: '34px',
    padding: '4px 6px',
    borderBottom: `1px solid ${desktopColor.wash}`,
  }),
  activeQueueItem: css({
    background: desktopColor.accentSoft,
    boxShadow: `3px 0 0 ${desktopColor.accent} inset`,
  }),
  trackButton: css({
    border: 0,
    background: 'transparent',
    width: '100%',
    height: 'auto',
    color: 'inherit',
    font: 'inherit',
    cursor: 'pointer',
    display: 'grid',
    gridTemplateColumns: '36px minmax(0, 1fr)',
    gap: '6px',
    alignItems: 'center',
    minWidth: 0,
    textAlign: 'left',
    padding: 0,
    '&:focus-visible': {
      outline: `2px solid ${desktopColor.accent}`,
      outlineOffset: '-2px',
    },
  }),
  queueIndex: css({ color: '#607077', fontVariantNumeric: 'tabular-nums' }),
  queueTrack: css({ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }),
  empty: css({
    margin: '10px',
    padding: '12px',
    border: `1px solid ${desktopColor.line}`,
    background: desktopColor.paper,
  }),
  person: css({
    display: 'flex',
    justifyContent: 'space-between',
    gap: '10px',
    padding: '5px 8px',
    borderBottom: `1px solid ${desktopColor.wash}`,
    background: '#fff',
    '& small': { color: '#465156' },
  }),
  gate: css({
    width: 'min(520px, 100%)',
    margin: '0 auto',
    display: 'grid',
    gap: '6px',
    padding: '4px',
  }),
  gateTitle: css({ margin: '6px 0 4px', fontSize: 'clamp(36px, 12vw, 58px)', lineHeight: 0.92 }),
  gateForm: css({
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 160px',
    gap: '4px',
    '@media (max-width: 520px)': {
      gridTemplateColumns: '1fr',
      '& button': { width: '100%' },
    },
  }),
  controlBar: css({
    display: 'grid',
    gap: '6px',
    padding: '6px',
    background: '#edf3f4',
    borderTop: `1px solid ${desktopColor.line}`,
    gridTemplateColumns: 'minmax(0, 1fr) 188px',
    alignItems: 'center',
    '& > div': { gridColumn: '1 / -1' },
    '@media (max-width: 560px)': { gridTemplateColumns: '1fr' },
  }),
  transport: css({
    display: 'grid',
    gridTemplateColumns: '34px 34px 34px minmax(0, 1fr)',
    gap: '5px',
    alignItems: 'center',
    '@media (max-width: 560px)': {
      gridTemplateColumns: '34px 34px 34px',
      '& div': { gridColumn: '1 / -1' },
    },
  }),
  transportReadout: css({
    display: 'grid',
    gridTemplateColumns: '64px minmax(0, 1fr)',
    gap: '8px',
    minWidth: 0,
    '& strong': {
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      fontWeight: 400,
    },
  }),
} as const
